name: sky color sign

on:
  schedule:
    - cron: '0 0 * * *' # 每天的UTC时间的午夜触发
  workflow_dispatch:

jobs:
  sky-color-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Generate random delay
        id: random_delay
        run: echo "::set-output name=delay::$((RANDOM % 1440))" # 在一天中的分钟数范围内生成随机数

      - name: Wait for random delay
        run: sleep ${{ steps.random_delay.outputs.delay }}m

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        run: python main.py
        env:
          Token: ${{ secrets.TOKEN }}

