name: sky color sign

on:
  schedule:
    - cron: '0 0 * * *' # 每天的UTC时间的午夜触发
  workflow_dispatch:

jobs:
  sky-color-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # - name: Random wait
      #   run: echo "Sleeping for $(( $RANDOM % 600 )) seconds" && sleep $(( $RANDOM % 600 ))


      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Execute Python Script
        run: python main.py
        env:
          Token: ${{ secrets.TOKEN }}

