#工作名字
name: sky-color
#
on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * *

jobs:
  #将工作流程中运行的所有作业组合在一起
  sky-color:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: sky color
        with:
          token: ${{ secrets.TOKEN }}
        run: |
          python3 ./main.py
        
